Repository spdx/spdx-spec, pull requests merged in 2024-11, with the labels that each got.

#1130 Add SPDX favicon.ico to the website
  docs/img/favicon.ico
Labels: website improvement

#1123 Change log update for v3.0.1 spec
  CHANGELOG.md
Labels: doc improvement

#1150 Fix indent in dependabot.yml
  .github/dependabot.yml
Labels: ci

#1151 Pause the publication workflow during the branch renaming
  .github/workflows/publish_v3.yml
Labels: ci

#1149 Add branch strategy to README
  README.md
Labels: doc improvement

#1153 Drop "v" from the 3.0.1 tag name in a link in change log
  CHANGELOG.md
Labels: doc improvement

#1146 Update publication CI for "develop" branch
  .github/workflows/publish_v3.yml
  requirements.txt
Labels: ci
