Repository spdx/spdx-spec, pull requests merged in 2024-09, with the labels that each got.

#1099 Preparing for submissions
  docs/front/index.md
  docs/front/introduction.md
  mkdocs.yml
  submissions/ISO/README.md
  submissions/ISO/annexes/changes-from-previous-iso.md
  submissions/ISO/front/iso-foreword.md
  submissions/OMG/README.md
  submissions/OMG/annexes/omg-history.md
  submissions/OMG/front/cover.md
  submissions/OMG/front/omg-preface.md
  submissions/OMG/front/second-page.md
  submissions/OMG/images/3tsbom-draft-core.png
  submissions/OMG/images/3tsbom-spdx30-correspondence.png
  submissions/OMG/images/spdx23-spdx30-comparison.png
  submissions/OMG/images/spdx30-draft-core.png
  submissions/OMG/people.md
  submissions/README.md
Labels: publishing, ci

#1101 [WEBSITE BROKEN] Fix 404 File Not Found for spec website homepage (root)
  docs/front/copyright.md
  docs/index.md
  mkdocs.yml
Labels: publishing, ci

#1098 Update example to 3.0.1
  examples/jsonld/package_sbom.json
Labels: doc improvement

#1106 Fix bad links related to abbreviations in References chapter
  docs/references.md
Labels: publishing

#1110 Fix typo in Lite annex: concludedLicense -> hasConcludedLicense
  docs/annexes/spdx-lite.md
Labels: publishing

#1111 Update examples validation to v3.0.1
  .github/workflows/validate_examples.yml
  bin/check-examples.sh
Labels: blocker, publishing, ci

#1117 Update shacl2code to 0.0.14
  requirements.txt
Labels: blocker, publishing, ci

#1090 Add missing para of JSON-LD context section to Model and serializations chapter
  docs/serializations.md
Labels: publishing

#1107 Remove heading numbering, fix internal refs, standardized RFC links
  docs/annexes/license-matching-guidelines-and-templates.md
  docs/annexes/pkg-url-specification.md
  docs/annexes/rdf-model.md
  docs/annexes/spdx-license-expressions.md
  docs/conformance.md
  docs/references.md
  docs/serializations.md
Labels: publishing

#1120 [Diagram] Remove all named individuals
  docs/images/model-core-software.png
  docs/images/model-licensing.png
Labels: publishing

#1126 Remove "License Information in File" from License List Matching guidelines
  docs/annexes/license-matching-guidelines-and-templates.md
Labels: publishing

#1128 Add Extension Profile diagram to Annex
  docs/annexes/rdf-model.md
Labels: publishing

#1129 Standardize RFC links to https://datatracker.ietf.org/doc/rfc...
  docs/annexes/pkg-url-specification.md
  docs/annexes/spdx-license-expressions.md
Labels: publishing
