Repository spdx/spdx-spec, pull requests merged in 2025-07, with the labels that each got.

#1220 [2.3.1] Publish schema doc
  .github/workflows/publish_common.yml
Labels: ci

#1222 [2.3] Fix broken Figure C.1 in Annex C
  chapters/RDF-object-model-and-identifier-syntax.md
  chapters/img/spdx-2.3-simplified.png
Labels: bug, website improvement

#1248 Update version in homepage to 3.1-dev
  docs/index.md
  setup.py
Labels: doc improvement

#1253 Remove personal pronoun use
  docs/front/introduction.md
Labels: ISO conformance

#1252 Update terms-and-definitions.md
  docs/terms-and-definitions.md
Labels: ISO conformance
